In [7]:
import pandas as pd
df = pd.read_csv("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.csv")
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [8]:
df.columns

Index(['Patron Type Code', 'Patron Type Definition', 'Total Checkouts',
       'Total Renewals', 'Age Range', 'Home Library Code',
       'Home Library Definition', 'Circulation Active Month',
       'Circulation Active Year', 'Notice Preference Code',
       'Notice Preference Definition', 'Provided Email Address',
       'Year Patron Registered', 'Outside of County', 'Supervisor District'],
      dtype='object')

In [9]:
df["Total Renewals"]

0       8
1       0
2       4
3      48
4      13
5       0
6      11
7       6
8     801
9       0
10      0
11      8
12      0
13      3
14      0
15      6
16      0
17      0
18      0
19      0
Name: Total Renewals, dtype: int64

In [10]:
df[['Total Renewals', 'Total Checkouts']]

    Total Renewals  Total Checkouts
0                8              518
1                0               38
2                4               38
3               48               48
4               13               28
5                0                1
6               11              293
7                6              900
8              801             1569
9                0               45
10               0                0
11               8               73
12               0               12
13               3               26
14               0                0
15               6               18
16               0              603
17               0                0
18               0                7
19               0                0

In [11]:
column_names = ['Total Renewals', 'Total Checkouts']
subset = df[column_names]
subset

    Total Renewals  Total Checkouts
0                8              518
1                0               38
2                4               38
3               48               48
4               13               28
5                0                1
6               11              293
7                6              900
8              801             1569
9                0               45
10               0                0
11               8               73
12               0               12
13               3               26
14               0                0
15               6               18
16               0              603
17               0                0
18               0                7
19               0                0

In [12]:
print(subset)

    Total Renewals  Total Checkouts
0                8              518
1                0               38
2                4               38
3               48               48
4               13               28
5                0                1
6               11              293
7                6              900
8              801             1569
9                0               45
10               0                0
11               8               73
12               0               12
13               3               26
14               0                0
15               6               18
16               0              603
17               0                0
18               0                7
19               0                0

In [13]:
x = df['Total Renewals']
df['Total Renewals'] = 5
x

0     5
1     5
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     5
10    5
11    5
12    5
13    5
14    5
15    5
16    5
17    5
18    5
19    5
Name: Total Renewals, dtype: int64

In [14]:
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,1,JUVENILE,518,5,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,JUVENILE,38,5,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,0,ADULT,38,5,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,0,ADULT,48,5,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,1,JUVENILE,28,5,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,1,JUVENILE,1,5,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,1,JUVENILE,293,5,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,1,JUVENILE,900,5,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,1,JUVENILE,1569,5,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,1,JUVENILE,45,5,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,1,JUVENILE,0,5,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,1,JUVENILE,73,5,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,1,JUVENILE,12,5,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,2,YOUNG ADULT,26,5,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,0,ADULT,0,5,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,3,SENIOR,18,5,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,1,JUVENILE,603,5,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,1,JUVENILE,0,5,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,1,JUVENILE,7,5,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,3,SENIOR,0,5,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [15]:
df['is_adult'] = df['Patron Type Definition'] == 'ADULT'
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District,is_adult
0,1,JUVENILE,518,5,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0,False
1,1,JUVENILE,38,5,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0,False
2,0,ADULT,38,5,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0,True
3,0,ADULT,48,5,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0,True
4,1,JUVENILE,28,5,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0,False
5,1,JUVENILE,1,5,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0,False
6,1,JUVENILE,293,5,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0,False
7,1,JUVENILE,900,5,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0,False
8,1,JUVENILE,1569,5,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0,False
9,1,JUVENILE,45,5,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0,False
10,1,JUVENILE,0,5,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0,False
11,1,JUVENILE,73,5,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0,False
12,1,JUVENILE,12,5,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0,False
13,2,YOUNG ADULT,26,5,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN,False
14,0,ADULT,0,5,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN,True
15,3,SENIOR,18,5,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0,False
16,1,JUVENILE,603,5,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0,False
17,1,JUVENILE,0,5,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0,False
18,1,JUVENILE,7,5,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0,False
19,3,SENIOR,0,5,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN,False

In [16]:
import numpy as np

df['log_renewals'] = np.log(df['Total Renewals'] + 1)
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District,is_adult,log_renewals
0,1,JUVENILE,518,5,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0,False,1.791759
1,1,JUVENILE,38,5,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0,False,1.791759
2,0,ADULT,38,5,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0,True,1.791759
3,0,ADULT,48,5,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0,True,1.791759
4,1,JUVENILE,28,5,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0,False,1.791759
5,1,JUVENILE,1,5,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0,False,1.791759
6,1,JUVENILE,293,5,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0,False,1.791759
7,1,JUVENILE,900,5,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0,False,1.791759
8,1,JUVENILE,1569,5,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0,False,1.791759
9,1,JUVENILE,45,5,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0,False,1.791759
10,1,JUVENILE,0,5,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0,False,1.791759
11,1,JUVENILE,73,5,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0,False,1.791759
12,1,JUVENILE,12,5,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0,False,1.791759
13,2,YOUNG ADULT,26,5,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN,False,1.791759
14,0,ADULT,0,5,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN,True,1.791759
15,3,SENIOR,18,5,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0,False,1.791759
16,1,JUVENILE,603,5,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0,False,1.791759
17,1,JUVENILE,0,5,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0,False,1.791759
18,1,JUVENILE,7,5,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0,False,1.791759
19,3,SENIOR,0,5,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN,False,1.791759

In [17]:
df['Circulation Active Year'] = pd.to_numeric(df['Circulation Active Year'], errors='coerce')
df['Circulation Active Year']

# Codebeispiel im Skript reicht nicht, um im Dataframe umzusetzen, es muss immer die 
# zu behandelnde Variable als neue definiert werden, s.a. unten für pd.to_datetime und .dt.month

0     2016.0
1     2016.0
2     2008.0
3     2013.0
4     2016.0
5     2016.0
6     2016.0
7     2016.0
8     2016.0
9     2016.0
10       NaN
11    2016.0
12    2015.0
13    2015.0
14       NaN
15    2015.0
16    2016.0
17       NaN
18    2013.0
19       NaN
Name: Circulation Active Year, dtype: float64

In [18]:
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District,is_adult,log_renewals
0,1,JUVENILE,518,5,10 to 19 years,V3,Visitacion Valley,July,2016.0,p,phone,False,2010,False,10.0,False,1.791759
1,1,JUVENILE,38,5,0 to 9 years,P1,Park,June,2016.0,z,email,True,2015,False,4.0,False,1.791759
2,0,ADULT,38,5,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008.0,z,email,True,2003,False,8.0,True,1.791759
3,0,ADULT,48,5,20 to 24 years,O7,Ortega,February,2013.0,p,phone,False,2004,False,10.0,True,1.791759
4,1,JUVENILE,28,5,0 to 9 years,E9,Excelsior,June,2016.0,z,email,True,2014,False,11.0,False,1.791759
5,1,JUVENILE,1,5,10 to 19 years,M4,Merced,May,2016.0,z,email,True,2016,False,11.0,False,1.791759
6,1,JUVENILE,293,5,0 to 9 years,M6,Mission,June,2016.0,z,email,True,2014,False,8.0,False,1.791759
7,1,JUVENILE,900,5,0 to 9 years,V3,Visitacion Valley,June,2016.0,a,print,False,2011,False,10.0,False,1.791759
8,1,JUVENILE,1569,5,10 to 19 years,W4,Western Addition,July,2016.0,z,email,True,2009,False,8.0,False,1.791759
9,1,JUVENILE,45,5,0 to 9 years,A5,Anza,June,2016.0,z,email,True,2015,False,1.0,False,1.791759
10,1,JUVENILE,0,5,0 to 9 years,S7,Sunset,None,NaN,p,phone,False,2015,False,7.0,False,1.791759
11,1,JUVENILE,73,5,0 to 9 years,P3,Parkside,July,2016.0,z,email,True,2015,False,4.0,False,1.791759
12,1,JUVENILE,12,5,0 to 9 years,X,Main Library,October,2015.0,z,email,True,2015,False,6.0,False,1.791759
13,2,YOUNG ADULT,26,5,10 to 19 years,M4,Merced,November,2015.0,z,email,True,2009,False,NaN,False,1.791759
14,0,ADULT,0,5,10 to 19 years,M4,Merced,None,NaN,z,email,True,2015,True,NaN,True,1.791759
15,3,SENIOR,18,5,75 years and over,W2,West Portal,June,2015.0,p,phone,False,2003,False,7.0,False,1.791759
16,1,JUVENILE,603,5,0 to 9 years,X,Main Library,July,2016.0,a,print,False,2012,False,11.0,False,1.791759
17,1,JUVENILE,0,5,0 to 9 years,A5,Anza,None,NaN,z,email,True,2015,False,1.0,False,1.791759
18,1,JUVENILE,7,5,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013.0,p,phone,False,2013,False,10.0,False,1.791759
19,3,SENIOR,0,5,75 years and over,S7,Sunset,None,NaN,z,email,True,2008,True,NaN,False,1.791759

In [19]:
df['Circulation Active Month'] = pd.to_datetime(
    df['Circulation Active Month'],
    errors='coerce',
    format="%B")

In [20]:
df['Circulation Active Month'] = df['Circulation Active Month'].dt.month

In [21]:
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District,is_adult,log_renewals
0,1,JUVENILE,518,5,10 to 19 years,V3,Visitacion Valley,7.0,2016.0,p,phone,False,2010,False,10.0,False,1.791759
1,1,JUVENILE,38,5,0 to 9 years,P1,Park,6.0,2016.0,z,email,True,2015,False,4.0,False,1.791759
2,0,ADULT,38,5,10 to 19 years,N4,Noe Valley/Sally Brunn,11.0,2008.0,z,email,True,2003,False,8.0,True,1.791759
3,0,ADULT,48,5,20 to 24 years,O7,Ortega,2.0,2013.0,p,phone,False,2004,False,10.0,True,1.791759
4,1,JUVENILE,28,5,0 to 9 years,E9,Excelsior,6.0,2016.0,z,email,True,2014,False,11.0,False,1.791759
5,1,JUVENILE,1,5,10 to 19 years,M4,Merced,5.0,2016.0,z,email,True,2016,False,11.0,False,1.791759
6,1,JUVENILE,293,5,0 to 9 years,M6,Mission,6.0,2016.0,z,email,True,2014,False,8.0,False,1.791759
7,1,JUVENILE,900,5,0 to 9 years,V3,Visitacion Valley,6.0,2016.0,a,print,False,2011,False,10.0,False,1.791759
8,1,JUVENILE,1569,5,10 to 19 years,W4,Western Addition,7.0,2016.0,z,email,True,2009,False,8.0,False,1.791759
9,1,JUVENILE,45,5,0 to 9 years,A5,Anza,6.0,2016.0,z,email,True,2015,False,1.0,False,1.791759
10,1,JUVENILE,0,5,0 to 9 years,S7,Sunset,NaN,NaN,p,phone,False,2015,False,7.0,False,1.791759
11,1,JUVENILE,73,5,0 to 9 years,P3,Parkside,7.0,2016.0,z,email,True,2015,False,4.0,False,1.791759
12,1,JUVENILE,12,5,0 to 9 years,X,Main Library,10.0,2015.0,z,email,True,2015,False,6.0,False,1.791759
13,2,YOUNG ADULT,26,5,10 to 19 years,M4,Merced,11.0,2015.0,z,email,True,2009,False,NaN,False,1.791759
14,0,ADULT,0,5,10 to 19 years,M4,Merced,NaN,NaN,z,email,True,2015,True,NaN,True,1.791759
15,3,SENIOR,18,5,75 years and over,W2,West Portal,6.0,2015.0,p,phone,False,2003,False,7.0,False,1.791759
16,1,JUVENILE,603,5,0 to 9 years,X,Main Library,7.0,2016.0,a,print,False,2012,False,11.0,False,1.791759
17,1,JUVENILE,0,5,0 to 9 years,A5,Anza,NaN,NaN,z,email,True,2015,False,1.0,False,1.791759
18,1,JUVENILE,7,5,0 to 9 years,B2,Bayview/Linda Brooks-Burton,12.0,2013.0,p,phone,False,2013,False,10.0,False,1.791759
19,3,SENIOR,0,5,75 years and over,S7,Sunset,NaN,NaN,z,email,True,2008,True,NaN,False,1.791759

In [22]:
df['Membership Duration'] = (
    df['Circulation Active Year'] - df['Year Patron Registered'])*12 + df['Circulation Active Month']

In [23]:
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District,is_adult,log_renewals,Membership Duration
0,1,JUVENILE,518,5,10 to 19 years,V3,Visitacion Valley,7.0,2016.0,p,phone,False,2010,False,10.0,False,1.791759,79.0
1,1,JUVENILE,38,5,0 to 9 years,P1,Park,6.0,2016.0,z,email,True,2015,False,4.0,False,1.791759,18.0
2,0,ADULT,38,5,10 to 19 years,N4,Noe Valley/Sally Brunn,11.0,2008.0,z,email,True,2003,False,8.0,True,1.791759,71.0
3,0,ADULT,48,5,20 to 24 years,O7,Ortega,2.0,2013.0,p,phone,False,2004,False,10.0,True,1.791759,110.0
4,1,JUVENILE,28,5,0 to 9 years,E9,Excelsior,6.0,2016.0,z,email,True,2014,False,11.0,False,1.791759,30.0
5,1,JUVENILE,1,5,10 to 19 years,M4,Merced,5.0,2016.0,z,email,True,2016,False,11.0,False,1.791759,5.0
6,1,JUVENILE,293,5,0 to 9 years,M6,Mission,6.0,2016.0,z,email,True,2014,False,8.0,False,1.791759,30.0
7,1,JUVENILE,900,5,0 to 9 years,V3,Visitacion Valley,6.0,2016.0,a,print,False,2011,False,10.0,False,1.791759,66.0
8,1,JUVENILE,1569,5,10 to 19 years,W4,Western Addition,7.0,2016.0,z,email,True,2009,False,8.0,False,1.791759,91.0
9,1,JUVENILE,45,5,0 to 9 years,A5,Anza,6.0,2016.0,z,email,True,2015,False,1.0,False,1.791759,18.0
10,1,JUVENILE,0,5,0 to 9 years,S7,Sunset,NaN,NaN,p,phone,False,2015,False,7.0,False,1.791759,NaN
11,1,JUVENILE,73,5,0 to 9 years,P3,Parkside,7.0,2016.0,z,email,True,2015,False,4.0,False,1.791759,19.0
12,1,JUVENILE,12,5,0 to 9 years,X,Main Library,10.0,2015.0,z,email,True,2015,False,6.0,False,1.791759,10.0
13,2,YOUNG ADULT,26,5,10 to 19 years,M4,Merced,11.0,2015.0,z,email,True,2009,False,NaN,False,1.791759,83.0
14,0,ADULT,0,5,10 to 19 years,M4,Merced,NaN,NaN,z,email,True,2015,True,NaN,True,1.791759,NaN
15,3,SENIOR,18,5,75 years and over,W2,West Portal,6.0,2015.0,p,phone,False,2003,False,7.0,False,1.791759,150.0
16,1,JUVENILE,603,5,0 to 9 years,X,Main Library,7.0,2016.0,a,print,False,2012,False,11.0,False,1.791759,55.0
17,1,JUVENILE,0,5,0 to 9 years,A5,Anza,NaN,NaN,z,email,True,2015,False,1.0,False,1.791759,NaN
18,1,JUVENILE,7,5,0 to 9 years,B2,Bayview/Linda Brooks-Burton,12.0,2013.0,p,phone,False,2013,False,10.0,False,1.791759,12.0
19,3,SENIOR,0,5,75 years and over,S7,Sunset,NaN,NaN,z,email,True,2008,True,NaN,False,1.791759,NaN

In [24]:
df['Membership Duration'] = df['Membership Duration'].fillna(0)
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District,is_adult,log_renewals,Membership Duration
0,1,JUVENILE,518,5,10 to 19 years,V3,Visitacion Valley,7.0,2016.0,p,phone,False,2010,False,10.0,False,1.791759,79.0
1,1,JUVENILE,38,5,0 to 9 years,P1,Park,6.0,2016.0,z,email,True,2015,False,4.0,False,1.791759,18.0
2,0,ADULT,38,5,10 to 19 years,N4,Noe Valley/Sally Brunn,11.0,2008.0,z,email,True,2003,False,8.0,True,1.791759,71.0
3,0,ADULT,48,5,20 to 24 years,O7,Ortega,2.0,2013.0,p,phone,False,2004,False,10.0,True,1.791759,110.0
4,1,JUVENILE,28,5,0 to 9 years,E9,Excelsior,6.0,2016.0,z,email,True,2014,False,11.0,False,1.791759,30.0
5,1,JUVENILE,1,5,10 to 19 years,M4,Merced,5.0,2016.0,z,email,True,2016,False,11.0,False,1.791759,5.0
6,1,JUVENILE,293,5,0 to 9 years,M6,Mission,6.0,2016.0,z,email,True,2014,False,8.0,False,1.791759,30.0
7,1,JUVENILE,900,5,0 to 9 years,V3,Visitacion Valley,6.0,2016.0,a,print,False,2011,False,10.0,False,1.791759,66.0
8,1,JUVENILE,1569,5,10 to 19 years,W4,Western Addition,7.0,2016.0,z,email,True,2009,False,8.0,False,1.791759,91.0
9,1,JUVENILE,45,5,0 to 9 years,A5,Anza,6.0,2016.0,z,email,True,2015,False,1.0,False,1.791759,18.0
10,1,JUVENILE,0,5,0 to 9 years,S7,Sunset,NaN,NaN,p,phone,False,2015,False,7.0,False,1.791759,0.0
11,1,JUVENILE,73,5,0 to 9 years,P3,Parkside,7.0,2016.0,z,email,True,2015,False,4.0,False,1.791759,19.0
12,1,JUVENILE,12,5,0 to 9 years,X,Main Library,10.0,2015.0,z,email,True,2015,False,6.0,False,1.791759,10.0
13,2,YOUNG ADULT,26,5,10 to 19 years,M4,Merced,11.0,2015.0,z,email,True,2009,False,NaN,False,1.791759,83.0
14,0,ADULT,0,5,10 to 19 years,M4,Merced,NaN,NaN,z,email,True,2015,True,NaN,True,1.791759,0.0
15,3,SENIOR,18,5,75 years and over,W2,West Portal,6.0,2015.0,p,phone,False,2003,False,7.0,False,1.791759,150.0
16,1,JUVENILE,603,5,0 to 9 years,X,Main Library,7.0,2016.0,a,print,False,2012,False,11.0,False,1.791759,55.0
17,1,JUVENILE,0,5,0 to 9 years,A5,Anza,NaN,NaN,z,email,True,2015,False,1.0,False,1.791759,0.0
18,1,JUVENILE,7,5,0 to 9 years,B2,Bayview/Linda Brooks-Burton,12.0,2013.0,p,phone,False,2013,False,10.0,False,1.791759,12.0
19,3,SENIOR,0,5,75 years and over,S7,Sunset,NaN,NaN,z,email,True,2008,True,NaN,False,1.791759,0.0