In [1]:
import pandas as pd
df = pd.read_csv("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.csv")
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [12]:
x = pd.Series([34, 12, 23, 45])
print(x)
x.dtype

0    34
1    12
2    23
3    45
dtype: int64

dtype('int64')

### Aufgabe 2.2: Skalenniveau und Datentypen

In [ ]:
# Skalenniveaus: nominalskaliert = month, below_zero; intervallskaliert = temp
# Variablen: diskret = month, below_zero; stetig = temp
# Datentypen: s.u.

In [13]:
data = {'month': ['Jan', 'Feb', 'Mar'],
        'temp': [-5, 2, 3],
         'below_zero': [True, False, False]}
df = pd.DataFrame(data)
print(df)

  month  temp  below_zero
0   Jan    -5        True
1   Feb     2       False
2   Mar     3       False

In [18]:
data = {'month': ['Jan', 'Feb', 'Mar', 'Apr'],
        'temp': [-5, 2, 3, 5],
         'below_zero': [True, False, False, False],
           'year': [2020, 2020, 2020, 2020]}
df = pd.DataFrame(data)
print(df)

  month  temp  below_zero  year
0   Jan    -5        True  2020
1   Feb     2       False  2020
2   Mar     3       False  2020
3   Apr     5       False  2020

In [16]:
df.dtypes

month         object
temp           int64
below_zero      bool
dtype: object

### Aufgabe 2.3: Exkurs: Datenrundreise

In [2]:
import pandas as pd
df = pd.read_csv("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.csv")
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [5]:
df.to_json("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.json")

In [7]:
dfjson = pd.read_json("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.json")
dfjson

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [8]:
dfjson.to_html("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.html")

In [10]:
dfhtml = pd.read_html("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.html")
dfhtml

[    Unnamed: 0  Patron Type Code Patron Type Definition  Total Checkouts  \
 0            0                 1               JUVENILE              518
 1            1                 1               JUVENILE               38
 2            2                 0                  ADULT               38
 3            3                 0                  ADULT               48
 4            4                 1               JUVENILE               28
 5            5                 1               JUVENILE                1
 6            6                 1               JUVENILE              293
 7            7                 1               JUVENILE              900
 8            8                 1               JUVENILE             1569
 9            9                 1               JUVENILE               45
 10          10                 1               JUVENILE                0
 11          11                 1               JUVENILE               73
 12          12                 1               JUVENILE               12
 13          13                 2            YOUNG ADULT               26
 14          14                 0                  ADULT                0
 15          15                 3                 SENIOR               18
 16          16                 1               JUVENILE              603
 17          17                 1               JUVENILE                0
 18          18                 1               JUVENILE                7
 19          19                 3                 SENIOR                0

     Total Renewals          Age Range Home Library Code  \
 0                8     10 to 19 years                V3
 1                0       0 to 9 years                P1
 2                4     10 to 19 years                N4
 3               48     20 to 24 years                O7
 4               13       0 to 9 years                E9
 5                0     10 to 19 years                M4
 6               11       0 to 9 years                M6
 7                6       0 to 9 years                V3
 8              801     10 to 19 years                W4
 9                0       0 to 9 years                A5
 10               0       0 to 9 years                S7
 11               8       0 to 9 years                P3
 12               0       0 to 9 years                 X
 13               3     10 to 19 years                M4
 14               0     10 to 19 years                M4
 15               6  75 years and over                W2
 16               0       0 to 9 years                 X
 17               0       0 to 9 years                A5
 18               0       0 to 9 years                B2
 19               0  75 years and over                S7

         Home Library Definition Circulation Active Month  \
 0             Visitacion Valley                     July
 1                          Park                     June
 2        Noe Valley/Sally Brunn                 November
 3                        Ortega                 February
 4                     Excelsior                     June
 5                        Merced                      May
 6                       Mission                     June
 7             Visitacion Valley                     June
 8              Western Addition                     July
 9                          Anza                     June
 10                       Sunset                     None
 11                     Parkside                     July
 12                 Main Library                  October
 13                       Merced                 November
 14                       Merced                     None
 15                  West Portal                     June
 16                 Main Library                     July
 17                         Anza                     None
 18  Bayview/Linda Brooks-Burton                 December
 19                       Sunset                     None

    Circulation Active Year Notice Preference Code  \
 0                     2016                      p
 1                     2016                      z
 2                     2008                      z
 3                     2013                      p
 4                     2016                      z
 5                     2016                      z
 6                     2016                      z
 7                     2016                      a
 8                     2016                      z
 9                     2016                      z
 10                    None                      p
 11                    2016                      z
 12                    2015                      z
 13                    2015                      z
 14                    None                      z
 15                    2015                      p
 16                    2016                      a
 17                    None                      z
 18                    2013                      p
 19                    None                      z

    Notice Preference Definition  Provided Email Address  \
 0                         phone                   False
 1                         email                    True
 2                         email                    True
 3                         phone                   False
 4                         email                    True
 5                         email                    True
 6                         email                    True
 7                         print                   False
 8                         email                    True
 9                         email                    True
 10                        phone                   False
 11                        email                    True
 12                        email                    True
 13                        email                    True
 14                        email                    True
 15                        phone                   False
 16                        print                   False
 17                        email                    True
 18                        phone                   False
 19                        email                    True

     Year Patron Registered  Outside of County  Supervisor District
 0                     2010              False                 10.0
 1                     2015              False                  4.0
 2                     2003              False                  8.0
 3                     2004              False                 10.0
 4                     2014              False                 11.0
 5                     2016              False                 11.0
 6                     2014              False                  8.0
 7                     2011              False                 10.0
 8                     2009              False                  8.0
 9                     2015              False                  1.0
 10                    2015              False                  7.0
 11                    2015              False                  4.0
 12                    2015              False                  6.0
 13                    2009              False                  NaN
 14                    2015               True                  NaN
 15                    2003              False                  7.0
 16                    2012              False                 11.0
 17                    2015              False                  1.0
 18                    2013              False                 10.0
 19                    2008               True                  NaN  ]

In [15]:
dfhtml[0]

,Unnamed: 0,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [16]:
dfhtml[0].to_excel("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.xlsx")
dfexcel = pd.read_excel("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small.xlsx")
dfexcel

,Unnamed: 0,Unnamed: 0.1,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,2,2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,3,3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,4,4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,5,5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,6,6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,7,7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,8,8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,9,9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,10,10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,11,11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,12,12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,13,13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,14,14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,15,15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,16,16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,17,17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,18,18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,19,19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [17]:
dfexcel.to_csv("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small_endofjourney.csv")

In [19]:
dfcsv = pd.read_csv("/home/schumahe/Schumacher/Modul_3/data/Library_Usage_Small_endofjourney.csv")
dfcsv

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,0,0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,1,1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,2,2,2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,3,3,3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,4,4,4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,5,5,5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,6,6,6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,7,7,7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,8,8,8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,9,9,9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,10,10,10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,11,11,11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,12,12,12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,13,13,13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,14,14,14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,15,15,15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,16,16,16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,17,17,17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,18,18,18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,19,19,19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

### Aufgabe 2.4: Exkurs Arbeitsspeicher

In [21]:
# Bash Befehle:
# free -m = MB
# free -b = Byte
# free -g = GB
#free -help = alle Optionen
# top = CPU/RAM-Werte in Echtzeit inkl. aller tätigen Anwendungen
#####
# freier Arbeitsspeicher: 115453952 Byte = 14431744 int64-Werte = 144317.44, also 144317 Beobachtungen

In [23]:
df.memory_usage(deep=True)

Index                            128
Patron Type Code                 160
Patron Type Definition          1290
Total Checkouts                  160
Total Renewals                   160
Age Range                       1404
Home Library Code               1178
Home Library Definition         1346
Circulation Active Month        1238
Circulation Active Year         1220
Notice Preference Code          1160
Notice Preference Definition    1240
Provided Email Address            20
Year Patron Registered           160
Outside of County                 20
Supervisor District              160
dtype: int64