## Modul 3: Aufgabe 1.5, Ãœbung Pandas

In [1]:
# import the library and give it a shorter name 'pd'
import pandas as pd

# create a dataframe by hand with two columns and three rows
df = pd.DataFrame({
        'month': [1, 2, 3],
        'temperatur': [-12, 3, 9]
})

# print out some descriptive statistics
df.describe()

       month  temperatur
count    3.0    3.000000
mean     2.0    0.000000
std      1.0   10.816654
min      1.0  -12.000000
25%      1.5   -4.500000
50%      2.0    3.000000
75%      2.5    6.000000
max      3.0    9.000000

In [2]:
# import the library and give it a shorter name 'pd'
import pandas as pd

# create a dataframe by hand with two columns and three rows
df = pd.DataFrame({
        'month': [1, 2, 3, 7, 8, 10],
        'temperatur': [-12, 3, 9, 25, 30, 9]
})

# print out some descriptive statistics
df.describe()

           month  temperatur
count   6.000000    6.000000
mean    5.166667   10.666667
std     3.656045   15.214029
min     1.000000  -12.000000
25%     2.250000    4.500000
50%     5.000000    9.000000
75%     7.750000   21.000000
max    10.000000   30.000000